default:
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
stages:
  - build
  - push
variables:    
  DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  
build:
  stage: build
  script:
    - docker build -t us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest .
  tags:
    - docker

push:
  stage: push
  script:
    - gcloud auth configure-docker us-east1-docker.pkg.dev
    - docker push us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest
  tags:
    - docker

