default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest .
  tags:
    - docker

push:
  stage: push
  script:
    - gcloud auth configure-docker us-east1-docker.pkg.dev
    - docker push us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest
  tags:
    - docker

