image: docker:24-git
services:
    - docker:24-dind
variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
    FF_NETWORK_PER_BUILD: "true"  
before_script:
    - until docker info > /dev/null 2>&1; do sleep 1; done
stages:
  - build_push

build_push:
  stage: build_push  # Renamed the stage to match the stages section
  script:
    - while ! nc -z localhost 2375; do sleep 0.1; done
    - docker build -t us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest .
    - gcloud auth configure-docker us-east1-docker.pkg.dev
    - docker push us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest

