default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
stages:
  - build
  - push   

build:
  script:
    - docker build -t flaskapp3  .
push:
  script:
    - docker tag flaskapp3 us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3
    - gcloud auth configure-docker us-east1-docker.pkg.dev
    - docker push us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3

