image: gcr.io/google.com/cloudsdktool/google-cloud-cli:466.0.0-alpine
services:
    - docker:19-dind
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2  
      # DOCKER_TLS_VERIFY: 1
      #DOCKER_CERT_PATH: "/certs/client"
    FF_NETWORK_PER_BUILD: "true"  
stages:
  - build_push

build_push:
  stage: build_push  # Renamed the stage to match the stages section
  script:
    - docker build -t us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest .
    - gcloud auth configure-docker us-east1-docker.pkg.dev
    - docker push us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest

