image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build_push

build_push:
  stage: build
  script:
    - docker build -t us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest .
    - gcloud auth configure-docker us-east1-docker.pkg.dev
    - docker push us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest

