stages:
  - run_command

run_command:
  stage: run_command
  image: alpine:latest  # Use an image that includes the necessary tools for your command

  script:
    - echo "Running my simple Linux command"
    - ls  # Replace with the actual command you want to run

