image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: "tcp://localhost:2375"  # Corrected DOCKER_HOST value
    #  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build_push

build_push:
  stage: build_push  # Renamed the stage to match the stages section
  script:
    - while ! nc -z localhost 2375; do sleep 0.1; done
    - docker build -t us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest .
    - gcloud auth configure-docker us-east1-docker.pkg.dev
    - docker push us-east1-docker.pkg.dev/trans-vehicle-418406/argorollouts/flaskapp3:latest

